Repository welsh-revenue-authority/component-library, pull requests merged in 2024-10, with the labels that each got.

#90 🦺 Undefined and null checks on component initialisation
  src/components/Autocomplete.vue
  src/components/CheckboxGroup.vue
  src/components/Radio.vue
  src/components/RadioGroup.vue
  src/components/Select.vue
Labels: bug

#89 🧪 Component tests
  cypress.config.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  package-lock.json
  package.json
  src/components/componentTests/Components.cy.js
Labels: test

#91 ✨ new feature: custom file upload
  src/components/FileUpload.vue
  src/stories/FileUpload.stories.js
Labels: enhancement

#88 ✨ new feature: skip link component
  lib/main.js
  src/components/SkipLink.vue
  src/index.js
  src/stories/SkipLink.stories.js
Labels: enhancement

#85 ✨ new feature: add inset component
  lib/main.js
  src/components/Inset.vue
  src/index.js
  src/stories/Inset.stories.js
Labels: enhancement

#96 🧪 improvement to some component tests
  cypress/fixtures/ComponentFixtures.json
  src/components/componentTests/Components.cy.js
Labels: test

#98 🩹 fix: add native file input attributes to FileUpload
  package.json
  src/components/FileUpload.vue
Labels: enhancement
