Repository welsh-revenue-authority/component-library, pull requests merged in 2024-04, with the labels that each got.

#5 Replace Rollup with Vite
  .storybook/main.js
  index.html
  lib/main.js
  package-lock.json
  package.json
  rollup.config.js
  vite.config.js
Labels: enhancement, needs review

#7 Prevent storybook build from running on all pull request activity
  .github/workflows/build-artifact.yaml
Labels: bug, needs review

#9 Add NPM publish workflow
  .github/workflows/build-npm-artifact.yaml
  .github/workflows/build-storybook.yaml
  package-lock.json
  package.json
Labels: enhancement

#1 Add Tab and Tabs
  lib/main.js
  src/components/Tab.vue
  src/components/Tabs.vue
  src/stories/Tabs.stories.js
Labels: enhancement

#4 Add breadcrumbs
  lib/main.js
  src/components/Breadcrumbs.vue
  src/index.js
  src/stories/Breadcrumbs.stories.js
Labels: enhancement

#15 Change input padding and center align content
  src/components/NumberInput.vue
  src/components/PriceInput.vue
Labels: enhancement

#16 Add service logo
  lib/main.js
  src/components/ServiceLogo.vue
  src/stories/ServiceLogo.stories.js
  src/stories/assets/wg-logo.svg
  src/stories/assets/wra-logo-english.svg
Labels: enhancement

#13 Add button prepend and append icon
  lib/main.js
  src/components/Button.vue
  src/components/ExpansionPanel.vue
  src/components/Subheader.vue
  src/index.js
  src/stories/Button.stories.js
Labels: enhancement

#21 Add custom start page
  src/stories/Configure.mdx
  src/stories/GettingStarted.mdx
Labels: documentation

#11 Add snackbar
  lib/main.js
  src/components/Snackbar.vue
  src/index.js
  src/stories/Snackbar.stories.js
Labels: enhancement

#19 Add banner
  lib/main.js
  src/components/Banner.vue
  src/index.js
  src/stories/Banner.stories.js
Labels: enhancement
